name: SFDX Test Run on Push

on: [push]

jobs:
  test:
  
    runs-on: ubuntu-latest
    
    steps:
      - name: Validate branch name requirements
        uses: deepakputhraya/action-branch-name@master
        with:
            regex: '([a-zA-Z])+\/([a-zA-Z])+'
            min_length: 6